export const path = {
  //public
  HOME: "/",
  AUCTION: "/auction",
  BLOG: "/blog",
  ABOUT: "/about",
  LOGIN: "/login",
  SIGNUP: "/signup",
  AUCTIONSCREENDETAIL: "/AuctionDetails",
  //breeder
  BREEDER: "breeder",
  CREATEREQUEST: "CreateRequest",
  HISTORYREQUEST: "HistoryRequest",
  DETAILREQUEST: "DetailRequest",
  PAYMENTRESPONSE: "PaymentResponse",
  FISHLIST: "FishList",
  DETAILFISH: "DetailFish",
  //manage
  MANAGER: "/Manager",
  MANAGE: "Manage",
  USERDETAIL: "UserDetail",
  MANAGEAUCTION: "ManageAuction",
  CREATEAUCTION: "CreateAuction",
  MANAGEBREEDER: "ManageBreeder",
  AUCTIONDETAIL: "AuctionDetail",
  BREEDERDETAIL: "BreederDetail",
  CREATEBREEDER: "CreateBreeder",
  MANAGEREQUEST: "ManageRequest",
  REQUESTDETAIL: "RequestDetail",
  MANAGEKOI: "ManageKoi",
  KOIDETAIL: "KoiDetail",
  MANAGEFISHENTRY: "ManageFishEntry",
  FISHENTRYDETAIL: "FishEntryDetail",
  //
  AUCTIONMETHOD3: "/AuctionFishMethod3",
  AUCTIONMETHOD2: "/AuctionFishMethod2",
  AUCTIONMETHOD1: "/AuctionFishMethod1",
};
